files = [
    "TypedefAndTypeAliases",
    "ArithmeticOperators",
    "TypeConversion",
    "UserInput",
    "UsefulMathFunctions",
    "HypotenuseCalculator",
    "IfStatements",
    "SwitchStatements",
    "ConsoleCalculator",
    "TernaryOperator",
    "LogicalOperators",
    "TemperatureConversion",
    "StringMethods",
    "WhileLoops",
    "DoWhileLoops",
    "ForLoops",
    "BreakAndContinue",
    "NestedLoops",
    "RandomNumberGenerator",
    "RandomEventGenerator",
    "NumberGuessingGame",
    "UserDefinedFunctions",
    "ReturnKeyword",
    "OverloadedFunctions",
    "VariableScope",
    "BankingProgram",
    "RockPaperScissors",
    "Arrays",
    "SizeofOperator",
    "IterateOverArray",
    "ForeachLoop",
    "PassArrayToFunction",
    "SearchArray",
    "SortArray",
    "FillFunction",
    "FillArrayWithInput",
    "MultidimensionalArrays",
    "QuizGame",
    "MemoryAddresses",
    "PassByValueVsReference",
    "ConstParameters",
    "CreditCardValidator",
    "Pointers",
    "NullPointers",
    "TicTacToe",
    "DynamicMemory",
    "Recursion",
    "FunctionTemplates",
    "Structs",
    "PassStructsAsArguments",
    "Enums",
    "ObjectOrientedProgramming",
    "Constructors",
    "ConstructorOverloading",
    "GettersAndSetters",
    "Inheritance"
]

for file in files:
    with open(f"{file}.cpp","w") as f:
        f.write(" ")

print("Files created successfully")